/**
 * Deal stages represent the lifecycle of a B2B deal
 */
export enum DealStage {
  INGESTION = 'ingestion',
  ENRICHMENT = 'enrichment',
  SCOPING = 'scoping',
  PROPOSAL = 'proposal',
  CRM_SYNC = 'crm_sync',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

/**
 * Core Deal entity representing a B2B opportunity
 */
export interface Deal {
  id: string;
  stage: DealStage;
  createdAt: Date;
  updatedAt: Date;

  // Lead information
  leadEmail: string;
  leadName: string;
  leadCompany?: string;
  leadTitle?: string;

  // Communication
  threadId?: string;
  initialEmailId?: string;

  // Enrichment data
  companyResearch?: CompanyResearch;
  prospectResearch?: ProspectResearch;

  // Scoping data
  projectScope?: ProjectScope;
  requirements?: Requirement[];

  // Proposal data
  proposal?: Proposal;
  proposalDocumentId?: string;

  // CRM sync
  crmId?: string;
  crmSyncedAt?: Date;

  // Metadata
  source: 'gmail' | 'manual' | 'other';
  assignedAgent?: string;
  approvalStatus?: 'pending' | 'approved' | 'rejected';
}

/**
 * Input for creating a new deal
 */
export interface DealInput {
  leadEmail: string;
  leadName: string;
  leadCompany?: string;
  leadTitle?: string;
  threadId?: string;
  initialEmailId?: string;
  source: 'gmail' | 'manual' | 'other';
}

/**
 * Company research data from enrichment
 */
export interface CompanyResearch {
  companyName: string;
  industry?: string;
  size?: string;
  website?: string;
  description?: string;
  recentNews?: string[];
  fundingInfo?: {
    stage?: string;
    amount?: number;
    date?: Date;
  };
  technologies?: string[];
  competitors?: string[];
}

/**
 * Prospect research data from enrichment
 */
export interface ProspectResearch {
  name: string;
  title: string;
  LinkedIn?: string;
  tenure?: string;
  background?: string;
  recentActivity?: string[];
  decisionMaker: boolean;
  influenceLevel: 'high' | 'medium' | 'low';
}

/**
 * Project scope from scoping agent
 */
export interface ProjectScope {
  title: string;
  description: string;
  timeline?: string;
  budgetRange?: string;
  complexity: 'low' | 'medium' | 'high';
  services: string[];
  deliverables: string[];
  assumptions: string[];
  risks: string[];
}

/**
 * Individual requirement extracted from scoping
 */
export interface Requirement {
  id: string;
  category: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  status: 'identified' | 'clarified' | 'confirmed';
  clarification?: string;
}

/**
 * Proposal generated by proposal agent
 */
export interface Proposal {
  title: string;
  executiveSummary: string;
  scope: string;
  timeline: string;
  pricing: PricingBreakdown;
  terms: string[];
  nextSteps: string[];
}

/**
 * Pricing breakdown for proposal
 */
export interface PricingBreakdown {
  currency: string;
  total: number;
  breakdown: {
    service: string;
    amount: number;
    description?: string;
  }[];
  paymentSchedule?: string;
}
